language: node_js
node_js:
  - "lts/*"
  - "8"

env:
  - PACKAGE=gcode-toolbox-cli
  - PACKAGE=gcode-toolbox-gcode
  - PACKAGE=gcode-toolbox-process

script:
  - lerna run build --scope $PACKAGE
  - lerna run test --scope $PACKAGE
